let productimage = document.getElementById('product-image')
productimage.src = sessionStorage.getItem('detailSrc')
let productprice = document.getElementById('product-price')
productprice.innerHTML = sessionStorage.getItem('detailPrice')
let productdescription = document.getElementById('product-description')
productdescription.innerHTML = sessionStorage.getItem('detailDescription')
let sellername = document.getElementById('seller-name')
sellername.innerHTML = sessionStorage.getItem('name')
let sellercontact = document.getElementById('seller-contact')
sellercontact.innerHTML = sessionStorage.getItem('detailContact')
let companyname = document.getElementById('product-companyname')
companyname.innerHTML = sessionStorage.getItem('detailName')
let selleraddress = document.getElementById('seller-address')
selleraddress.innerHTML = sessionStorage.getItem('detailAddress')


let getback = document.getElementById('back')
getback.addEventListener('click',()=>{
    sessionStorage.removeItem('detailSrc')
    sessionStorage.removeItem('detailPrice')
    sessionStorage.removeItem('detailDescription')
    sessionStorage.removeItem('detailContact')
    sessionStorage.removeItem('detailAddress')
    sessionStorage.removeItem('detailName')
    window.history.back()
})